"""create groups reports permissions tables

Revision ID: 245d941e5608
Revises: 7b7554b0d057
Create Date: 2026-06-23 09:07:47.763113

"""
from alembic import op
import sqlalchemy as sa


revision = '245d941e5608'
down_revision = '7b7554b0d057'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_folders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('folder_type', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['bip.report_folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name'),
    schema='bip'
    )
    op.create_table('user_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='bip'
    )
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('workspace_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('workspace_id'),
    schema='bip'
    )
    op.create_table('datasets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['bip.workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'dataset_id'),
    schema='bip'
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('report_id', sa.String(length=128), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=True),
    sa.Column('dataset_id', sa.String(length=128), nullable=True),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['bip.report_folders.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['bip.workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'report_id'),
    schema='bip'
    )
    op.create_table('report_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['bip.reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'subject_type', 'subject_id', 'permission'),
    schema='bip'
    )
    op.create_table('user_group_members',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['bip.user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['bip.users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    sa.UniqueConstraint('group_id', 'user_id'),
    schema='bip'
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_members', schema='bip')
    op.drop_table('report_permissions', schema='bip')
    op.drop_table('reports', schema='bip')
    op.drop_table('datasets', schema='bip')
    op.drop_table('workspaces', schema='bip')
    op.drop_table('user_groups', schema='bip')
    op.drop_table('report_folders', schema='bip')
    # ### end Alembic commands ###
