"""alter refresh_runs time columns to timestamptz

Revision ID: 6c7e9e71b76b
Revises: 72480dba612c
Create Date: 2026-06-23 16:20:06.429597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6c7e9e71b76b'
down_revision = '72480dba612c'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_runs', 'start_time_utc',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='bip')
    op.alter_column('refresh_runs', 'end_time_utc',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='bip')
    op.alter_column('refresh_runs', 'start_time_local',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='bip')
    op.alter_column('refresh_runs', 'end_time_local',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='bip')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_runs', 'end_time_local',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='bip')
    op.alter_column('refresh_runs', 'start_time_local',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='bip')
    op.alter_column('refresh_runs', 'end_time_utc',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='bip')
    op.alter_column('refresh_runs', 'start_time_utc',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='bip')
    # ### end Alembic commands ###
