"""create audit logs and requests tables

Revision ID: 72480dba612c
Revises: 95871c47ad53
Create Date: 2026-06-23 09:56:05.734797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '72480dba612c'
down_revision = '95871c47ad53'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('occurred_at_utc', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bip'
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False, schema='bip')
    op.create_index('idx_audit_action_occurred', 'audit_logs', ['action', 'occurred_at_utc'], unique=False, schema='bip')
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_user_id'], unique=False, schema='bip')
    op.create_index('idx_audit_occurred_at', 'audit_logs', ['occurred_at_utc'], unique=False, schema='bip')
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False, schema='bip')
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('request_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('operator_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bip'
    )
    op.create_index('idx_requests_requester', 'requests', ['requester_id'], unique=False, schema='bip')
    op.create_index('idx_requests_status', 'requests', ['status'], unique=False, schema='bip')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_requests_status', table_name='requests', schema='bip')
    op.drop_index('idx_requests_requester', table_name='requests', schema='bip')
    op.drop_table('requests', schema='bip')
    op.drop_index('idx_audit_resource', table_name='audit_logs', schema='bip')
    op.drop_index('idx_audit_occurred_at', table_name='audit_logs', schema='bip')
    op.drop_index('idx_audit_actor', table_name='audit_logs', schema='bip')
    op.drop_index('idx_audit_action_occurred', table_name='audit_logs', schema='bip')
    op.drop_index('idx_audit_action', table_name='audit_logs', schema='bip')
    op.drop_table('audit_logs', schema='bip')
    # ### end Alembic commands ###
