"""create refresh mail job tables

Revision ID: 95871c47ad53
Revises: 245d941e5608
Create Date: 2026-06-23 09:47:07.941809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '95871c47ad53'
down_revision = '245d941e5608'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=True),
    sa.Column('end_time_utc', sa.DateTime(), nullable=True),
    sa.Column('start_time_local', sa.DateTime(), nullable=True),
    sa.Column('end_time_local', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'dataset_id', 'request_id'),
    schema='bip'
    )
    op.create_table('refresh_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('days', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('times', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'dataset_id'),
    schema='bip'
    )
    op.create_table('mail_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject_template', sa.String(length=500), nullable=True),
    sa.Column('body_header', sa.Text(), nullable=True),
    sa.Column('body_footer', sa.Text(), nullable=True),
    sa.Column('image_width', sa.String(length=32), nullable=True),
    sa.Column('image_resize_px', sa.Integer(), nullable=True),
    sa.Column('cron_expr', sa.String(length=128), nullable=True),
    sa.Column('export_format', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['bip.reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bip'
    )
    op.create_table('mail_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mail_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('run_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mail_schedule_id'], ['bip.mail_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail_schedule_id', 'run_key'),
    schema='bip'
    )
    op.create_table('mail_recipients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mail_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_type', sa.String(length=16), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(recipient_type = 'EMAIL' AND email IS NOT NULL AND recipient_id IS NULL) OR (recipient_type <> 'EMAIL' AND recipient_id IS NOT NULL AND email IS NULL)", name='ck_mail_recipient_type'),
    sa.ForeignKeyConstraint(['mail_schedule_id'], ['bip.mail_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail_schedule_id', 'recipient_type', 'recipient_id', 'email'),
    schema='bip'
    )
    op.create_table('mail_schedule_pages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mail_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('image_width_override', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mail_schedule_id'], ['bip.mail_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail_schedule_id', 'page_name'),
    schema='bip'
    )
    op.create_table('export_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mail_job_id', sa.BigInteger(), nullable=True),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('export_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mail_job_id'], ['bip.mail_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail_job_id', 'page_name'),
    schema='bip'
    )
    op.create_table('report_image_paths',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mail_job_id', sa.BigInteger(), nullable=True),
    sa.Column('export_job_id', sa.BigInteger(), nullable=True),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('variant', sa.String(length=16), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['export_job_id'], ['bip.export_jobs.id'], ),
    sa.ForeignKeyConstraint(['mail_job_id'], ['bip.mail_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bip'
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_image_paths', schema='bip')
    op.drop_table('export_jobs', schema='bip')
    op.drop_table('mail_schedule_pages', schema='bip')
    op.drop_table('mail_recipients', schema='bip')
    op.drop_table('mail_jobs', schema='bip')
    op.drop_table('mail_schedules', schema='bip')
    op.drop_table('refresh_schedules', schema='bip')
    op.drop_table('refresh_runs', schema='bip')
    # ### end Alembic commands ###
